[GCAN]
DLL_File=ControlCAN_GC.dll
DeviceType=4
DeviceInd=0

[CX]
DLL_File=ControlCAN_CX.dll
DeviceType=4
DeviceInd=0

[ZLG]
DLL_File=ControlCAN_ZLG.dll
DeviceType=4
DeviceInd=0

[ZLG_EU]
DLL_File=ControlCAN_ZLG_EU.dll
DeviceType=21
DeviceInd=0

[Tiny]
DLL_File=ControlCAN_Tiny.dll
DeviceType=4
DeviceInd=0


; 3: USBCAN_1 4: USBCAN_2 
; 20: USBCAN_1E 21: USBCAN_2E 